### ISSUE TITLE
DCS Not Loading as an Addon

### ISSUE THREAD

**Issue by bolerro** [dejoblue/DejaCharacterStats#154]
Downloaded the latest version of DCS from Wowinterface (800r116) through Minion and the addon is not showing up in my Addons screen within WOW.

I've cleaned out all my addons to start fresh as well as removing the cache, WTF and Interface folders to start fresh. Still will not show up as an addon.

**Comment by dejoblue** [comment]
Sorry, I haven't updated WoWInterface or Tuk/ElvUI yet.

Try downloading from Curse: https://wow.curseforge.com/projects/dejacharacterstats

**Comment by bolerro** [comment]
Thanks for the quick reply, I will continue to get it from Curse from now on
