### ISSUE TITLE
Make "Add NPC panel open and close events so that on-item repair totals update properly(it isn't a caching issues)." to have a bullet before it.

### ISSUE THREAD

**Issue by dejoblue** [dejoblue/DejaCharacterStats#24]
Make "Add NPC panel open and close events so that on-item repair totals update properly(it isn't a caching issues)." to have a bullet before it.

**Comment by Kakjens** [comment]
Adding a bullet was meant in addon description.

**Comment by dejoblue** [comment]
Kakjens fixed this.
