### ISSUE TITLE
New Low Level Mastery Issue

### ISSUE THREAD

**Issue by dejoblue** [dejoblue/DejaCharacterStats#59]
I merged many new pulls into 720Beta but now mastery is only hidden for Mastery Rating on my low level characters. Regular mastery is still yellow on low level characters.

**Comment by Kakjens** [comment]
Not exactly clear what did you mean here but I believe there are inconsistences in displaying mastery and mastery rating names for low level characters. Found a possible reason why it happens. But first will probably need to check that everything what was intended for merging is merged.
Edit. Interesting that in not-merged version I see the correct code.

**Comment by Kakjens** [comment]
Fixed in #61
